name: pdf_collage
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  image_picker: ^0.8.5+3
  pdf: ^3.8.1
  share_plus: ^4.0.10
  path_provider: ^2.0.11
  go_router: ^4.1.0
  meta: ^1.7.0
  flutter_hooks: ^0.18.5+1
  equatable: ^2.0.3
  reorderables: ^0.5.0
  badges: ^2.0.3
  styled_widget: ^0.4.0+3
  collection: ^1.16.0
  printing: ^5.9.1
  bloc: ^8.0.3
  path: ^1.8.1
  intl: ^0.17.0
  syncfusion_flutter_pdfviewer: ^20.1.61-beta
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  